### ISSUE TITLE
Tilling & container support

### ISSUE THREAD

**Issue by Gaspard--** [raven-os/feathers#19]

**Comment by Gaspard--** [comment]
Some progress with #20 
We now need:
- [x] shortcuts to manipulate it (see #21)
  - [x] change window floating status (co-goal with #19)
  - [x] change window tilling style (co-goal with #19)
  - [x] open next window below / right (co-goal with #19)
- [ ] setting the hint for the client to be border-less
- [x] allowing resize

Unclear if needed yet:
- [ ] custom borders

**Comment by Gaspard--** [comment]
Gonna close, the two last points are basicly #96
