### ISSUE TITLE
Key bindings

### ISSUE THREAD

**Issue by Gaspard--** [raven-os/feathers#22]
Bindings we need:
- [x] close current window
- [x] open default terminal
- [x] change window floating status (co-goal with #19)
- [x] change window tilling style (co-goal with #19)
- [x] movement key shortcuts
- [x] movement keys to switch between foreground and background
- [x] open next window below / right (co-goal with #19)

Relevant issues
#21 
#19 (see above)

**Comment by Gaspard--** [comment]
Seems we got them all!
